Homework 04 - Add bastion host to GCP
Otus-DevOps-2018-02/biosid_infra pull request #2
Opened 2018-03-15 15:31 UTC by biosid

# Выполнено ДЗ №4

- [x] Основное ДЗ
 - [ ] Задание со *

## PR checklisk
 - [x] Выставил label gcp
 - [x] Выставил label homework-04

2018-03-17 15:09 UTC, chromko requested changes
Привет. Нужно предварительно выполнить ДЗ № 3 и добавить в нем .travis.yml для дальнейшей работы.

2018-03-22 10:19 UTC, vitkhab commented on setupvpn.sh
> +cat <<EOF> setupvpn.sh
Лишняя строчка

2018-03-22 10:19 UTC, vitkhab commented on setupvpn.sh
> +EOF
Лишняя строчка.
Нет пустой линии в конце файла.

2018-03-22 10:22 UTC, vitkhab commented on README.md
> +someinternalhost_IP = 10.164.0.3
Нет пустой строки в конце файла.

2018-03-22 10:37 UTC, vitkhab requested changes
Поправь, пожалуйста, форматирование в файлах и убери лишние строчки из `setupvpn.sh`.

У тебя получилось запустит и настроить vpn-сервер? Ни Travis, ни я не смогли подключиться по vpn к твоему стенду.
Для сдачи ДЗ, пожалуйста, добейся успешной проверки Travis. Нужна будет помощь - обращайся.

Не обязательно для засчитывания дз, но желательно. Добавь, пожалуйста, описание к своему PR.

2018-03-22 13:15 UTC, vitkhab approved these changes
Тесты поправил. Молодец!
Пожалуйста, в будущем описывай, что ты делаешь в своем PR.

Можно мерджить.

2018-03-22 13:17 UTC, chromko approved these changes

2018-03-22 13:43 UTC, merged